kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-only-secrets
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
