apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard-resources
  name: kuard-resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard-resources
  template:
    metadata:
      labels:
        app: kuard-resources
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard-amd64
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
